### ISSUE TITLE
test issue Vdovhyi

### ISSUE THREAD

**Issue by vdovhyi** [ros-kamach/baseimage_nginx_phpfpm#55]
1234

**Comment by ros-kamach** [comment]
Migrated to [Issue#1](https://github.com/vdovhyi/baseimage_nginx_phpfpm/issues/1)

**Comment by ros-kamach** [comment]
123

**Comment by ros-kamach** [comment]
Migrated to [Issue#3](https://github.com/vdovhyi/baseimage_nginx_phpfpm/issues/3)

**Comment by ros-kamach** [comment]
Migrated to [Issue#4](https://github.com/vdovhyi/baseimage_nginx_phpfpm/issues/4)

**Comment by ros-kamach** [comment]
Migrated to [Issue#4](https://github.com/vdovhyi/baseimage_nginx_phpfpm/issues/4)

**Comment by ros-kamach** [comment]
Migrated to [Issue#4](https://github.com/vdovhyi/baseimage_nginx_phpfpm/issues/4)
